# Generated by Django 2.1.3 on 2018-11-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeekStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('num_registered_users', models.IntegerField(default=0)),
                ('num_verified_users', models.IntegerField(default=0)),
                ('num_active_users', models.IntegerField(default=0)),
                ('num_returning_users', models.IntegerField(default=0)),
                ('num_search_requests', models.IntegerField(default=0)),
                ('num_users_searched', models.IntegerField(default=0)),
                ('num_likes', models.IntegerField(default=0)),
                ('num_dislikes', models.IntegerField(default=0)),
                ('num_clicks', models.IntegerField(default=0)),
                ('num_articles_only_clicked', models.IntegerField(default=0)),
                ('num_articles_clicked_liked', models.IntegerField(default=0)),
                ('num_articles_clicked_disliked', models.IntegerField(default=0)),
                ('num_articles', models.IntegerField(default=0)),
                ('num_recommendations', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['timestamp'],
                'get_latest_by': 'timestamp',
            },
        ),
    ]
