# Generated by Django 2.1.3 on 2022-05-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_usertextinput'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_classifier',
            field=models.BooleanField(default=True),
        ),
    ]
