# Generated by Django 2.1.3 on 2022-05-02 22:40

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('website', '0004_userprofile_default_classifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bert_Classifier',
            fields=[
                ('user', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='bert_classifier', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('path_clf', models.CharField(max_length=255)),
            ],
        ),
    ]
